# Generated by Django 5.2.4 on 2025-08-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='roll_number',
            field=models.IntegerField(default=1, help_text='Unique numeric roll number for the student', unique=True),
            preserve_default=False,
        ),
    ]
