# Generated by Django 5.2.4 on 2025-08-06 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_students_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstudent',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.adminhod'),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
