# Generated by Django 5.2 on 2025-08-21 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_remove_timetable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='student_management_app.faculty'),
            preserve_default=False,
        ),
    ]
