# Generated by Django 5.2.4 on 2025-08-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_notificationstaffs_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstaffs',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
