# Generated by Django 5.2.4 on 2025-08-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_notificationstaffs_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstudent',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
