# Generated by Django 5.2.4 on 2025-08-06 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_notificationstudent_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationstaffs',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.AlterField(
            model_name='staffs',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
