# Generated by Django 5.2.4 on 2025-08-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_rename_staff_id_notificationstaffs_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_assignment_marks',
            new_name='subject_exam_full_marks',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_exam_marks',
            new_name='subject_internal_full_marks',
        ),
    ]
