# Generated by Django 5.2.4 on 2025-08-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_rename_subject_assignment_marks_studentresult_subject_exam_full_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_exam_full_marks',
            new_name='exam_full_marks',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_internal_full_marks',
            new_name='internal_full_marks',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_assignment_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_exam_marks',
            field=models.FloatField(default=0),
        ),
    ]
