# Generated by Django 5.2.4 on 2025-08-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_rename_subject_exam_full_marks_studentresult_exam_full_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='exam_full_marks',
            new_name='subject_exam_full_marks',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='internal_full_marks',
            new_name='subject_internal_full_marks',
        ),
    ]
