# Generated by Django 5.2.4 on 2025-08-07 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_rename_exam_full_marks_studentresult_subject_exam_full_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_reports', to='student_management_app.students'),
        ),
    ]
