from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from student_management_app.HodViews import student_profile_view
from student_management_app import views, HodViews, ParentViews, StaffViews, StudentViews
from student_management_app.EditResultVIewClass import EditResultViewClass
from student_management_system import settings

urlpatterns = [
    path('demo',views.showDemoPage),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup_admin',views.signup_admin,name="signup_admin"),
    path('signup_student',views.signup_student,name="signup_student"),
    path('signup_staff',views.signup_staff,name="signup_staff"),
    path('do_admin_signup',views.do_admin_signup,name="do_admin_signup"),
    path('do_staff_signup',views.do_staff_signup,name="do_staff_signup"),
    path('do_signup_student',views.do_signup_student,name="do_signup_student"),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',views.ShowLoginPage,name="show_login"),
    path('get_user_details', views.GetUserDetails),
    path('logout_user', views.logout_user,name="logout"),
    path('doLogin/',views.doLogin,name="do_login"),
    path('manage_admin/', HodViews.manage_admin, name='manage_admin'),
    path('admin_home/',HodViews.admin_home,name="admin_home"),
    path('add_staff/',HodViews.add_staff,name="add_staff"),
    path('add_staff_save',HodViews.add_staff_save,name="add_staff_save"),
    path('check_staff_username/', views.check_staff_username, name='check_staff_username'),
    path('check_staff_email/', views.check_staff_email, name='check_staff_email'),
    path('check_staff_phone/', views.check_staff_phone, name='check_staff_phone'),
    path('add_course/', HodViews.add_course,name="add_course"),
    path('add_course_save', HodViews.add_course_save,name="add_course_save"),
    path('add_student', HodViews.add_student,name="add_student"),
    path('check_username/', views.check_username, name='check_username'),
    path('validate_password/', views.validate_password, name='validate_password'),
    path('check_email/', views.check_email, name='check_email'),
    path('check_phone/', views.check_phone, name='check_phone'),
    path('add_student_save', HodViews.add_student_save,name="add_student_save"),
    path('add_subject', HodViews.add_subject,name="add_subject"),
    path('print_student_records/', HodViews.print_student_records, name='print_student_records'),
    path('add_subject_save', HodViews.add_subject_save,name="add_subject_save"),
    path('manage_staff', HodViews.manage_staff,name="manage_staff"),
    path('delete_staff/<staff_id>', HodViews.delete_staff, name='delete_staff'),
    path('manage_student', HodViews.manage_student,name="manage_student"),
    path('course/<int:course_id>/students/pdf/', HodViews.course_students_pdf, name='course_students_pdf'),
    path('delete_student/<student_id>', HodViews.delete_student, name='delete_student'),
    path('manage_course', HodViews.manage_course,name="manage_course"),
    path('delete_course/<course_id>', HodViews.delete_course, name='delete_course'),
    path('manage_subject/', HodViews.manage_subject,name="manage_subject"),
    path('delete_subject/<subject_id>', HodViews.delete_subject, name='delete_subject'),
    path('edit_staff/<str:staff_id>', HodViews.edit_staff,name="edit_staff"),
    path('edit_staff_save', HodViews.edit_staff_save,name="edit_staff_save"),
    path('edit_student/<str:student_id>', HodViews.edit_student,name="edit_student"),
    path('edit_student_save', HodViews.edit_student_save,name="edit_student_save"),
    path('edit_subject/<str:subject_id>', HodViews.edit_subject,name="edit_subject"),
    path('edit_subject_save', HodViews.edit_subject_save,name="edit_subject_save"),
    path('edit_course/<str:course_id>', HodViews.edit_course,name="edit_course"),
    path('edit_course_save', HodViews.edit_course_save,name="edit_course_save"),
    path('manage_session', HodViews.manage_session,name="manage_session"),
    path('delete_session/<int:session_id>', HodViews.delete_session, name='delete_session'),
    path('edit_session/<int:session_id>', HodViews.edit_session, name='edit_session'),
    path('add_session_save', HodViews.add_session_save,name="add_session_save"),
    path('check_email_exist', HodViews.check_email_exist,name="check_email_exist"),
    path('check_username_exist', HodViews.check_username_exist,name="check_username_exist"),
    path('student_feedback_message', HodViews.student_feedback_message,name="student_feedback_message"),
    path('student_feedback_message_replied', HodViews.student_feedback_message_replied,name="student_feedback_message_replied"),
    path('staff_feedback_message', HodViews.staff_feedback_message,name="staff_feedback_message"),
    path('staff_feedback_message_replied', HodViews.staff_feedback_message_replied,name="staff_feedback_message_replied"),
    path('student_leave_view', HodViews.student_leave_view,name="student_leave_view"),
    path('staff_leave_view', HodViews.staff_leave_view,name="staff_leave_view"),
    path('staff_profile/<int:staff_id>/', HodViews.staff_profile_view, name='staff_profile_view'),
    path('parent_profile/<int:parent_id>/', HodViews.parent_profile_view, name='parent_profile_view'),
    path('student_approve_leave/<str:leave_id>', HodViews.student_approve_leave,name="student_approve_leave"),
    path('student_disapprove_leave/<str:leave_id>', HodViews.student_disapprove_leave,name="student_disapprove_leave"),
    path('staff_disapprove_leave/<str:leave_id>', HodViews.staff_disapprove_leave,name="staff_disapprove_leave"),
    path('staff_approve_leave/<str:leave_id>', HodViews.staff_approve_leave,name="staff_approve_leave"),
    path('admin_view_attendance', HodViews.admin_view_attendance,name="admin_view_attendance"),
    path('admin_get_attendance_dates', HodViews.admin_get_attendance_dates,name="admin_get_attendance_dates"),
    path('admin_get_attendance_student', HodViews.admin_get_attendance_student,name="admin_get_attendance_student"),
    path('add_admin/', HodViews.add_admin, name='add_admin'),
    path('manage_admin/', HodViews.manage_admin, name='manage_admin'),
    path('admin_profile/', HodViews.admin_profile, name='admin_profile'),
    path('admin_profile/<int:admin_id>/', HodViews.admin_profile_view, name='admin_profile_view'),
    path('student_profile/<int:student_id>/', HodViews.student_profile_view, name='student_profile_view'),
    path('edit_admin/<int:admin_id>/', HodViews.edit_admin, name='edit_admin'),
    path('delete_admin/<int:admin_id>/', HodViews.delete_admin, name='delete_admin'),
    path('admin_profile_save', HodViews.admin_profile_save,name="admin_profile_save"),
    path('admin_send_notification_staff', HodViews.admin_send_notification_staff,name="admin_send_notification_staff"),
    path('admin_send_notification_student', HodViews.admin_send_notification_student,name="admin_send_notification_student"),
    path('admin_send_notification_parent', HodViews.admin_send_notification_parent, name='admin_send_notification_parent'),
    path('send_student_notification/', HodViews.send_student_notification,name="send_student_notification"),
    path('send_staff_notification', HodViews.send_staff_notification,name="send_staff_notification"),
    path('send_parent_notification/', HodViews.send_parent_notification, name='send_parent_notification'),
    path('send_notification/', HodViews.send_notification, name='send_notification'),
    path('get_notifications/', HodViews.get_notifications, name='get_notifications'),
    path('get_unread_count/', HodViews.get_unread_count, name='get_unread_count'),
    
    #staff urls
    path('staff_home', StaffViews.staff_home, name="staff_home"),
    path('staff_take_attendance', StaffViews.staff_take_attendance, name="staff_take_attendance"),
    path('staff_update_attendance', StaffViews.staff_update_attendance, name="staff_update_attendance"),
    path('get_students', StaffViews.get_students, name="get_students"),
    path('get_attendance_dates', StaffViews.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_student', StaffViews.get_attendance_student, name="get_attendance_student"),
    path('save_attendance_data', StaffViews.save_attendance_data, name="save_attendance_data"),
    path('save_updateattendance_data', StaffViews.save_updateattendance_data, name="save_updateattendance_data"),
    path('staff_apply_leave', StaffViews.staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save', StaffViews.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback', StaffViews.staff_feedback, name="staff_feedback"),
    path('staff_feedback_save', StaffViews.staff_feedback_save, name="staff_feedback_save"),
    path('staff_profile', StaffViews.staff_profile, name="staff_profile"),
    path('staff_profile_save', StaffViews.staff_profile_save, name="staff_profile_save"),
    path('staff_fcmtoken_save', StaffViews.staff_fcmtoken_save, name="staff_fcmtoken_save"),
    path('staff_all_notification', StaffViews.staff_all_notification, name="staff_all_notification"),
    path('staff_add_result', StaffViews.staff_add_result, name="staff_add_result"),
    path('save_student_result', StaffViews.save_student_result, name="save_student_result"),
    path('edit_student_result', StaffViews.edit_student_result, name="edit_student_result"),
    path('get_students_for_result', StaffViews.get_students_for_result, name="get_students_for_result"),
    path('fetch_student_result', StaffViews.fetch_student_result, name="fetch_student_result"),
    path('fetch_result_student',StaffViews.fetch_result_student, name="fetch_result_student"),
    path('total_subject', StaffViews.total_subject, name="total_subject"),
    path('subject_students/<int:subject_id>', StaffViews.subject_students, name="subject_students"),
    path('student_attendance/<int:student_id>/<int:subject_id>', StaffViews.view_student_attendance, name="student_attendance"),
    path('student_result/<int:student_id>/<int:subject_id>', StaffViews.view_student_result, name="student_result"),
    path('subject_wise_results', StaffViews.subject_wise_results, name='subject_wise_results'),
    path('staff_send_reply', StaffViews.staff_send_reply, name='staff_send_reply'),
    path('subject_wise_results/<int:subject_id>', StaffViews.subject_wise_results_detail, name='subject_wise_results_detail'),
    path('staff_profile/', StaffViews.staff_profile, name='staff_profile'),

    
    path('student_home', StudentViews.student_home, name="student_home"),
    path('student_view_attendance', StudentViews.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post', StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('student_apply_leave', StudentViews.student_apply_leave, name="student_apply_leave"),
    path('student_apply_leave_save', StudentViews.student_apply_leave_save, name="student_apply_leave_save"),
    path('student_feedback', StudentViews.student_feedback, name="student_feedback"),
    path('student_feedback_save', StudentViews.student_feedback_save, name="student_feedback_save"),
    path('student_profile', StudentViews.student_profile, name="student_profile"),
    path('student_profile_save', StudentViews.student_profile_save, name="student_profile_save"),
    path('student_fcmtoken_save', StudentViews.student_fcmtoken_save, name="student_fcmtoken_save"),
    path('firebase-messaging-sw.js',views.showFirebaseJS,name="show_firebase_js"),
    path('student_all_notification',StudentViews.student_all_notification,name="student_all_notification"),
    path('mark_student_notifications_as_read', StudentViews.mark_student_notifications_as_read, name="mark_student_notifications_as_read"),
    path('student_view_result',StudentViews.student_view_result,name="student_view_result"),
    path('node_modules/canvas-designer/widget.html',StaffViews.returnHtmlWidget,name="returnHtmlWidget"),
    path('send_notification_reply', StudentViews.send_notification_reply, name='send_notification_reply'),
    path('student_view_subjects/', StudentViews.student_view_subjects, name='student_view_subjects'),
    path('testurl/',views.Testurl),
    
    # Parents URLs
    path('parent_home', ParentViews.parent_home, name='parent_home'),
    path('add_parent/', HodViews.add_parent, name='add_parent'),
    path('manage_children/', ParentViews.manage_children, name='manage_children'),
    path('parent_view_result/', ParentViews.parent_view_result, name='parent_view_result'),
    path('check_parent_username/', views.check_parent_username, name='check_parent_username'),
    path('check_parent_email/', views.check_parent_email, name='check_parent_email'),
    path('check_parent_phone/', views.check_parent_phone, name='check_parent_phone'),
    path('add_parent_save/', HodViews.add_parent_save, name='add_parent_save'),
    path('manage_parent/', HodViews.manage_parent, name='manage_parent'),
    path('edit_parent/<parent_id>/', HodViews.edit_parent, name='edit_parent'),
    path('edit_parent_save/', HodViews.edit_parent_save, name='edit_parent_save'),
    path('delete_parent/<parent_id>/', HodViews.delete_parent, name='delete_parent'),
    path('parent_feedback', ParentViews.parent_feedback, name="parent_feedback"),
    path('parent_feedback_save', ParentViews.parent_feedback_save, name="parent_feedback_save"),
    path('parent_profile/', ParentViews.parent_profile, name='parent_profile'),
    path('student_view_attendance', StudentViews.student_view_attendance_post, name='student_view_attendance_post'),
    path('parent_view_attendance_post', ParentViews.parent_view_attendance_post, name='parent_view_attendance_post'),
    path('view_attendance', ParentViews.parent_view_attendance, name='parent_view_attendance'),
    path('parent_manage_children/', ParentViews.parent_manage_children, name='parent_manage_children'),
    path('get_attendance_history/', StaffViews.get_attendance_history, name='get_attendance_history'),
    
    # Parent Communication URLs
    path('parent_feedback_message', HodViews.parent_feedback_message,name="parent_feedback_message"),
    path('parent_all_notification/', ParentViews.parent_all_notification, name='parent_all_notification'),
    path('mark_staff_notifications_as_read/', StaffViews.mark_staff_notifications_as_read, name='mark_staff_notifications_as_read'),
    path('send_parent_notification/', HodViews.send_parent_notification, name='send_parent_notification'),
    path('parent_feedback_message_replied', HodViews.parent_feedback_message_replied,name="parent_feedback_message_replied"),
    path('send_parent_notification_save', HodViews.send_parent_notification_save, name='send_parent_notification_save'),
    path('view_parent_feedback/', HodViews.view_parent_feedback, name='view_parent_feedback'),
    path('parent_feedback_reply/', HodViews.parent_feedback_reply, name='parent_feedback_reply'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
